2019-08-28 16:45:02,822-Logs.py-ERROR-123
NoneType: None
